name: phpstan
on: [push]

jobs:
  phpstan:
    strategy:
      matrix:
        include:
          - PHP_VERSION: php83-fpm
            MAGENTO_VERSION: 2.4.7
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/setup
        name: Setup Magento community edition
        id: setup
        with:
          php-version: ${{ matrix.PHP_VERSION }}
          magento-version: ${{ matrix.MAGENTO_VERSION }}

      - name: Run PHPStan
        run: docker exec ${{ steps.setup.outputs.docker-container-name }} /bin/bash -c "./vendor/bin/phpstan analyse --no-progress -c /data/extensions/*/phpstan.neon /data/extensions"
